trigger:
  branches:
    include:
      - main  # تأكدي من أن هذا هو اسم الفرع الصحيح في GitHub

pool:
  name: 'Demo'  # تأكدي من أن هذا هو اسم الـ Self-Hosted Agent لديك

stages:
- stage: Build
  displayName: 'Setup Environment'
  jobs:
  - job: Build
    steps:
    - checkout: self  # جلب الكود من GitHub

    - script: |
        python -m venv venv
        call venv\Scripts\activate
        pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Setup Python Environment & Install Dependencies'

- stage: Test
  displayName: 'Run Robot Framework Tests'
  dependsOn: Build
  jobs:
  - job: Test
    steps:
    - script: |
        call venv\Scripts\activate
        robot -d results TestProject/
      displayName: 'Run Tests'

- stage: Deploy
  displayName: 'Deploy or Save Artifacts'
  dependsOn: Test
  condition: succeeded()
  jobs:
  - job: Deploy
    steps:
    - publish: $(System.DefaultWorkingDirectory)/results
      artifact: test-results
      displayName: 'Save Test Results'
